### ISSUE TITLE
CSS break

### ISSUE THREAD

**Issue by Lokosang-wani** [Chiekjowk/learning-page#1]
I first had a problem when I added my part but when I tried pushing, I found out I'm already a commit late cause Ikay has pushed before me, so I pulled Ik's changes and it broke my code cause he had a different structre from what I got from Mustafa, however I managed to rework my section and fix it but still its having some minor css issues with Ik's layout. causing some css to break.
Also all the css have to be looked at it and some fixes need to be done, specially on Mustafa's section amd mine too.
![Screenshot 2024-11-23 130540](https://github.com/user-attachments/assets/bdfea0f9-cac1-4b12-aedd-4ffb1be28e4d)
![Screenshot 2024-11-23 130730](https://github.com/user-attachments/assets/3cc6a7c3-9e79-4e73-a447-072c83510ab9)

**Comment by Chiekjowk** [comment]
i solved it already
